// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jbnxH4kYGUb25Axg0q_1bkl_e9n5szE',
    appId: '1:592035396956:web:1256e4fc51fe74b655d599',
    messagingSenderId: '592035396956',
    projectId: 'heroquest-6a0e5',
    authDomain: 'heroquest-6a0e5.firebaseapp.com',
    databaseURL: 'https://heroquest-6a0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'heroquest-6a0e5.firebasestorage.app',
    measurementId: 'G-FHYDSBNBXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd2tRNj-imAL2HvWEylLh6uqAXbY7f3Wo',
    appId: '1:592035396956:android:f5fc3a00a46ab8c655d599',
    messagingSenderId: '592035396956',
    projectId: 'heroquest-6a0e5',
    databaseURL: 'https://heroquest-6a0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'heroquest-6a0e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD0XP2vcgpo0PFW9TXnkI8IkiUvr7XKKo',
    appId: '1:592035396956:ios:e9d8425dbeb9ec0c55d599',
    messagingSenderId: '592035396956',
    projectId: 'heroquest-6a0e5',
    databaseURL: 'https://heroquest-6a0e5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'heroquest-6a0e5.firebasestorage.app',
    iosBundleId: 'com.example.heroquest',
  );
}
